/// Typed route parameters for this route segment.
///
/// Auto-generated by the build script. Do not edit.
#[derive(Debug, Clone)]
pub struct Params {
    pub id: String,
}

pub mod index;
pub mod og_png;
