import 'dotenv/config';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { writeFileSync } from 'fs';
import { PageIndexer, R2Uploader, loadSubmissions } from './src/index.js';
import type { PageSnapshot } from './src/types.js';
import type { SubmissionInput } from './src/indexer.js';
import crypto from 'crypto';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Limit number of submissions to process (useful during development)
const limit = process.env.LIMIT ? parseInt(process.env.LIMIT, 10) : undefined;

// Output path for the generated SQL seed file
const outputPath = join(__dirname, '..', 'src', 'server', 'src', 'seeds', 'seed_apps.sql');

// Load submissions from CSV
const csvPath = join(__dirname, 'submissions.csv');
let submissions = loadSubmissions(csvPath);

if (limit && limit > 0) {
  submissions = submissions.slice(0, limit);
  console.log(`Limiting to first ${limit} submissions (set LIMIT env var to change)\n`);
}

// Initialize indexer
const indexer = new PageIndexer({
  openaiApiKey: process.env.OPENAI_API_KEY,
  anthropicApiKey: process.env.ANTHROPIC_API_KEY,
  concurrency: 3,
  timeout: 30000,
});

// Initialize R2 uploader (optional)
let r2Uploader: R2Uploader | undefined;
if (process.env.R2_ACCOUNT_ID && process.env.R2_ACCESS_KEY_ID && process.env.R2_SECRET_ACCESS_KEY) {
  r2Uploader = new R2Uploader({
    accountId: process.env.R2_ACCOUNT_ID,
    accessKeyId: process.env.R2_ACCESS_KEY_ID,
    secretAccessKey: process.env.R2_SECRET_ACCESS_KEY,
    bucketName: process.env.R2_BUCKET_NAME || 'promptathon-images',
    publicUrl: process.env.R2_PUBLIC_URL,
  });
  console.log('R2 uploader configured');
} else {
  console.log('R2 not configured - images will not be uploaded');
}

// Build submission inputs for the indexer
const submissionInputs: SubmissionInput[] = submissions.map((s) => ({
  url: s.appUrl,
  meta: {
    authorName: s.authorName,
    appName: s.appName,
    socialPostUrl: s.socialPostUrl,
  },
}));

// Collect SQL INSERT statements
const sqlStatements: string[] = [];
sqlStatements.push('-- Generated by the indexer. Do not edit manually.');
sqlStatements.push(`-- Generated at: ${new Date().toISOString()}`);
sqlStatements.push(`-- Submissions processed: ${submissionInputs.length}`);
sqlStatements.push('');

function escapeSql(str: string): string {
  return str.replace(/'/g, "''");
}

function sqlOpt(val: string | null | undefined): string {
  if (!val) return 'NULL';
  return `'${escapeSql(val)}'`;
}

// Emit function - collect SQL and optionally upload to R2
async function emit(snapshot: PageSnapshot): Promise<void> {
  if (snapshot.status === 'ok') {
    const imageId = crypto.createHash('md5').update(snapshot.url).digest('hex');

    // Upload images to R2 if configured
    if (r2Uploader) {
      try {
        await r2Uploader.uploadScreenshots(imageId, snapshot.screenshotLarge, snapshot.screenshotSmall);
        console.log(`  Uploaded screenshots: ${imageId}`);
      } catch (error) {
        console.error(`  Failed to upload screenshots:`, error instanceof Error ? error.message : error);
      }
    }

    // Extract canister_id from ICP URLs
    const canisterId = extractCanisterId(snapshot.url);

    const sql = `INSERT INTO app (url, canister_id, title, description, image_id, author_name, app_name, social_post_url) VALUES (${sqlOpt(snapshot.url)}, ${sqlOpt(canisterId)}, ${sqlOpt(snapshot.aiTitle)}, ${sqlOpt(snapshot.aiDescription)}, ${sqlOpt(imageId)}, ${sqlOpt(snapshot.submission.authorName)}, ${sqlOpt(snapshot.submission.appName)}, ${sqlOpt(snapshot.submission.socialPostUrl)});`;

    sqlStatements.push(sql);

    console.log(`[ok] ${snapshot.submission.appName} by ${snapshot.submission.authorName}`);
    console.log(`     ${snapshot.aiTitle}`);
  } else {
    console.error(`[error] ${snapshot.url}: ${snapshot.error}`);
  }
}

function extractCanisterId(url: string): string | null {
  const match = url.match(/https?:\/\/([a-z0-9-]+)\.(icp0\.io|ic0\.app|raw\.ic0\.app)/);
  if (match && match[1] && match[1].includes('-')) {
    return match[1];
  }
  return null;
}

// Run
console.log(`Starting indexer...`);
console.log(`  Submissions: ${submissionInputs.length}`);
console.log(`  Output: ${outputPath}\n`);

indexer
  .processSubmissions(submissionInputs, emit)
  .then(() => {
    // Write the SQL seed file
    writeFileSync(outputPath, sqlStatements.join('\n') + '\n', 'utf-8');
    console.log(`\nSeed file written: ${outputPath}`);
    console.log(`  ${sqlStatements.length - 3} INSERT statements`);
  })
  .catch((err) => console.error('\nFatal error:', err));
