/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const HeaderField = IDL.Tuple(IDL.Text, IDL.Text);
  const HttpRequest = IDL.Record({
    'url' : IDL.Text,
    'method' : IDL.Text,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HeaderField),
    'certificate_version' : IDL.Opt(IDL.Nat16),
  });
  const HttpResponse = IDL.Record({
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HeaderField),
    'status_code' : IDL.Nat16,
  });
  const App = IDL.Record({
    'id' : IDL.Int64,
    'title' : IDL.Text,
    'updated_at' : IDL.Int64,
    'canister_id' : IDL.Text,
    'description' : IDL.Text,
    'created_at' : IDL.Int64,
    'image_id' : IDL.Opt(IDL.Text),
  });
  const SearchResult = IDL.Variant({ 'Ok' : IDL.Vec(App), 'Err' : IDL.Text });
  
  return IDL.Service({
    'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
    'search_apps' : IDL.Func([IDL.Text], [SearchResult], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };