/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const App = IDL.Record({
    'id' : IDL.Int64,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'updated_at' : IDL.Int64,
    'author_name' : IDL.Opt(IDL.Text),
    'canister_id' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'created_at' : IDL.Int64,
    'image_id' : IDL.Opt(IDL.Text),
    'social_post_url' : IDL.Opt(IDL.Text),
    'app_name' : IDL.Opt(IDL.Text),
  });
  const GetAppResult = IDL.Variant({ 'Ok' : App, 'Err' : IDL.Text });
  const HeaderField = IDL.Tuple(IDL.Text, IDL.Text);
  const HttpRequest = IDL.Record({
    'url' : IDL.Text,
    'method' : IDL.Text,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HeaderField),
    'certificate_version' : IDL.Opt(IDL.Nat16),
  });
  const HttpResponse = IDL.Record({
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HeaderField),
    'status_code' : IDL.Nat16,
  });
  const SearchResult = IDL.Variant({ 'Ok' : IDL.Vec(App), 'Err' : IDL.Text });
  
  return IDL.Service({
    'get_app' : IDL.Func([IDL.Int64], [GetAppResult], ['query']),
    'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
    'http_request_update' : IDL.Func([HttpRequest], [HttpResponse], []),
    'list_apps' : IDL.Func([], [IDL.Vec(App)], ['query']),
    'search' : IDL.Func([IDL.Text], [SearchResult], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };