/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/server.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface App {
    id: bigint;
    title: string;
    updated_at: bigint;
    canister_id: string;
    description: string;
    created_at: bigint;
    image_id?: string;
}
export type SearchResult = {
    __kind__: "Ok";
    Ok: Array<App>;
} | {
    __kind__: "Err";
    Err: string;
};
export type HeaderField = [string, string];
export interface HttpRequest {
    url: string;
    method: string;
    body: Uint8Array;
    headers: Array<HeaderField>;
    certificate_version?: number;
}
export interface HttpResponse {
    body: Uint8Array;
    headers: Array<HeaderField>;
    status_code: number;
}
export interface serverInterface {
    http_request(request: HttpRequest): Promise<HttpResponse>;
    search_apps(arg0: string): Promise<SearchResult>;
}
import type { App as _App, HeaderField as _HeaderField, HttpRequest as _HttpRequest, SearchResult as _SearchResult } from "./declarations/server.did.d.ts";
export class Server implements serverInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async http_request(arg0: HttpRequest): Promise<HttpResponse> {
        const result = await this.actor.http_request(to_candid_HttpRequest_n1(arg0));
        return result;
    }
    async search_apps(arg0: string): Promise<SearchResult> {
        const result = await this.actor.search_apps(arg0);
        return from_candid_SearchResult_n3(result);
    }
}
function from_candid_App_n6(value: _App): App {
    return from_candid_record_n7(value);
}
function from_candid_SearchResult_n3(value: _SearchResult): SearchResult {
    return from_candid_variant_n4(value);
}
function from_candid_opt_n8(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n7(value: {
    id: bigint;
    title: string;
    updated_at: bigint;
    canister_id: string;
    description: string;
    created_at: bigint;
    image_id: [] | [string];
}): {
    id: bigint;
    title: string;
    updated_at: bigint;
    canister_id: string;
    description: string;
    created_at: bigint;
    image_id?: string;
} {
    return {
        id: value.id,
        title: value.title,
        updated_at: value.updated_at,
        canister_id: value.canister_id,
        description: value.description,
        created_at: value.created_at,
        image_id: record_opt_to_undefined(from_candid_opt_n8(value.image_id))
    };
}
function from_candid_variant_n4(value: {
    Ok: Array<_App>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<App>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n5(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_vec_n5(value: Array<_App>): Array<App> {
    return value.map((x)=>from_candid_App_n6(x));
}
function to_candid_HttpRequest_n1(value: HttpRequest): _HttpRequest {
    return to_candid_record_n2(value);
}
function to_candid_record_n2(value: {
    url: string;
    method: string;
    body: Uint8Array;
    headers: Array<HeaderField>;
    certificate_version?: number;
}): {
    url: string;
    method: string;
    body: Uint8Array;
    headers: Array<_HeaderField>;
    certificate_version: [] | [number];
} {
    return {
        url: value.url,
        method: value.method,
        body: value.body,
        headers: value.headers,
        certificate_version: value.certificate_version ? candid_some(value.certificate_version) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Server {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Server(actor);
}
