// This file is auto-generated by ic-sql-migrate
// Do not edit manually

pub mod seed_001_apps;

use ic_sql_migrate::Seed;

pub static SEEDS: &[Seed] = &[Seed::new("seed_001_apps", seed_001_apps::seed)];
